Disable test harness for lib target
knurling-rs/app-template pull request #51
Opened 2021-06-04 21:46 UTC by Sh3Rm4n

Without this change, if `testsuite/src/lib.rs` will be crated and `cargo
test` is invoked, cargo will try to link libtest with the crate.

As this crate is `no_std` and will usually be run for targets, where no
std library exists and therefor also no libtest, this will fail with an
error similar to this:

    error[E0463]: can't find crate for `test`

    error: aborting due to previous error

    For more information about this error, try `rustc --explain E0463`.
    error: could not compile `testsuite`

To circumvent this issue, disable the harness for lib as well.

2021-06-04 22:14 UTC, Sh3Rm4n commented
Maybe I should add a dummy lib.rs as well, so that `cargo test -p testsuite --lib` does work?

I'm thinking of something like this:

`src/lib.rs`:

```rust
#![no_std]
// relevant because cargo test will build an executable and would add a main function implictly otherwise?
#![no_main]
 
// now, that cargo tests searches for an entry-point "main" provide one
#[export_name = "main"] // <--- this whole invocation could also be replaced with #[defmt_test::tests] mod tests { ... } 
unsafe extern "C" fn __dummy_entry() -> ! {
    // as we do not intent to run any tests, just exit with success
    defmt_test::export::exit()
} 
```

2021-06-06 12:29 UTC, Urhengulas requested changes
Looks good.

Let's add a dummy `lib.rs`. What do you think about using `#[defmt_test::tests]`, cause it looks less scary?
```rust
#![no_std]

use {{crate_name}} as _; // memory layout + panic handler

#[defmt_test::tests]
mod tests {}
```

2021-06-06 14:15 UTC, Sh3Rm4n commented on testsuite/src/lib.rs
> +#![cfg_attr(test, no_main)]
I've had to add `no_main` because lib.rs will be compiled as an executable when calling `cargo test`.

2021-06-06 21:33 UTC, Urhengulas approved these changes
Thank you!

2021-06-06 21:33 UTC, merged